alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias sudo='sudo '
alias vim='nvim'
alias mysql-dev='mysql --defaults-file=~/.db/dev.cnf'
alias mysql-staging='mysql --defaults-file=~/.db/staging.cnf'
alias mysql-mpt-staging='mysql --defaults-file=~/.db/mpt-staging.cnf'
