alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias sudo='sudo '
alias vim='nvim'
alias mysql-dev='mysql --defaults-extra-file=~/.mysql/dev.cnf'
alias mysql-staging='mysql --defaults-extra-file=~/.mysql/staging.cnf'
alias mysql-mpt-staging='mysql --defaults-extra-file=~/.mysql/mpt-staging.cnf'
